### PR TITLE
Package MenuPin as a stand alone add-on

### PR DESCRIPTION
**Pull request by ghost**
Refactored the packaging script so that it generates a stand alone
add-on that can be installed to a site rather than into the developer's
code base.

Also removed auto generated files from the git repository.

### CODE REVIEW

**Comment by ghost** [comment]
Guess your build doesn't like me moving the nuspec file. I can probably change it so that nuspec file remains where it was.

**Comment by ghost** [comment]
I see you pushed the CMS 10 compatibility. I will need to rebase to get a green build I guess.

**Comment by davidknipe** [comment]
Yeah sorry about that one Ben, forgot to push the updates after I released - I'd never make a proper dev you know ;)

The AppVeyor build was already broken so you are safe to ignore that one!

**Comment by davidknipe** [comment]
Also I maybe missing something but the changes appear to show that the MenupinInit.js file has been removed. Am I reading it wrong and/or got this wrong :S?

**Comment by ghost** [comment]
I removed the copied versions of the files and added the Package folder to the git ignore. It is usually good practice to exclude things from the repository that are generated by build task.

**Comment by marisks** [comment]
Any update on this pull request? Now MenuPin causes custom gadgets to fail to load the dashboard. And the cause is that it is not as a standalone module.

**Comment by davidknipe** [comment]
I will review this pull request asap, I've been too busy of late!

**Comment by nicklasisraelsson** [comment]
@davidknipe @ben-mckernan is on parental leave at the moment so you will have to rebase this PR yourself. 

I also hope that this PR and the one I just opened (#3) can be merged soon as EPiServers developer support has been involved with troubleshooting these issues.

**Comment by davidknipe** [comment]
Hi @marisks hope this solves the issue now. Let me know if you have any further issues!

**Comment by marisks** [comment]
Thanks all! No conflicts with gadgets anymore!

**Pull request merged**
